name: mtgo-db
services:
  postgres:
    image: postgres:latest
    container_name: postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # Performance settings
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 512MB
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: 0.7
      POSTGRES_WAL_BUFFERS: 16MB
      POSTGRES_RANDOM_PAGE_COST: 1.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Main entrypoint for initializing the database
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
      # Include additional SQL files in /pg
      - ./postgres/extensions.sql:/pg/extensions.sql:ro
      - ./postgres/schema.sql:/pg/schema.sql:ro
      - ./postgres/indexes.sql:/pg/indexes.sql:ro
      # Mount dump directory for migrations
      - ./postgres/dump:/pg/dump:ro
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cloudflared
  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer-prod
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      POOL_MODE: session
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      LISTEN_PORT: '${POSTGRES_PORT:-6432}'
      AUTH_TYPE: scram-sha-256
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-6432}:${POSTGRES_PORT:-6432}"
    networks:
      - cloudflared
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    depends_on:
      - pgbouncer
    command: tunnel --no-autoupdate run
    environment:
      - CLOUDFLARED_TUNNEL_NAME=${CLOUDFLARED_TUNNEL_NAME}
      - CLOUDFLARED_TUNNEL_ID=${CLOUDFLARED_TUNNEL_ID}
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - cloudflared
networks:
  cloudflared:
    driver: bridge
volumes:
  postgres-data:
